resources:
  - repo: self

trigger: none

pr:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
      - functions/*
      - coverage/*
      - .*

jobs:
  ##
  # Testing pipeline for PRs validation only.
  ##
  - job: Testing_pipeline
    timeoutInMinutes: 60
    cancelTimeoutInMinutes: 10

    pool:
      vmImage: 'ubuntu-16.04'

    steps:
      - task: NodeTool@0
        displayName: 'Use specific node version'
        inputs:
          versionSpec: '12.16.1'

      - script: |
          npm install -g npm@6.14.4
          yarn install --frozen-lockfile
          npm i -g typescript @angular/cli
          ng test

      - task: ArchiveFiles@2
        displayName: 'Archive files'
        inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
          includeRootFolder: false

      - task: PublishBuildArtifacts@1
        displayName: 'Publish artifacts: drop'
